Vagrant.configure('2') do |config|

  unless Vagrant.has_plugin?("vagrant-vbguest")
    puts 'Vagrant \'vagrant-vbguest\' is required but is not installed'
    puts 'please check if you have the plugin with the following command:'
    puts '    $ vagrand plugin list'
    puts 'If needed install the plugin:'
    puts '    $ vagrant plugin install vagrant-vbguest'
    abort 'Missing vagrant-vbguest plugin'
  end

  @min_memory = 256
  @min_cores = 1 
  config.ssh.insert_key = false

  config.vm.box     = "common-wheezy"
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end
  config.vm.box_url = "https://www.dropbox.com/s/l9gygl0c93g48fi/common.box?dl=1"
  config.ssh.forward_agent = true
  config.vm.box_check_update = true
  config.vbguest.auto_update = false

    config.vm.define 'graylog' do |graylog|
      graylog.vm.network 'private_network', ip: '10.10.10.10'
      graylog.vm.provider 'virtualbox' do |vb|
        vb.memory = @min_memory * 30
        vb.cpus = @min_cores * 8
      end
    end

end

# vi: set ft=ruby :
