Vagrant.configure('2') do |config|

  @min_memory = 256
  @min_cores = 1 
 
  config.vm.box     = "debian-wheezy"

    config.vm.define 'web' do |web|
      web.vm.network 'private_network', ip: '10.10.10.10'
      web.vm.provider 'virtualbox' do |vb|
        vb.memory = @min_memory * 4
        vb.cpus = @min_cores * 1
      end
    end
    
    config.vm.define 'db' do |db|
      config.vm.box     = "centos65x64"
      db.vm.network 'private_network', ip: '10.10.10.12'
      db.vm.provider 'virtualbox' do |vb|
        vb.memory = @min_memory * 4
        vb.cpus = @min_cores * 2
      end
    end

    config.vm.define 'cache' do |cache|
      cache.vm.network 'private_network', ip: '10.10.10.13'
      cache.vm.provider 'virtualbox' do |vb|
        vb.memory = @min_memory * 1
        vb.cpus = @min_cores * 1
      end
      config.vm.provision :ansible do |ansible|
        ansible.playbook = "vim.yml"
        ansible.limit = 'all'
        ansible.groups = {
          "web" => ["web"],
          "db"  => ["db"],
          "cache" => ["cache"],
          "all:children" => ["web", "db", "cache"]
        }
      end
    end

end

# vi: set ft=ruby :
